inspirehep/inspire-docker

python_base/Dockerfile
* Now the python-base image is based on centos reproducing the env we
have in production
Signed-off-by: David Caro <david.caro@cern.ch>
=> python-base: move to centos

python_base/Dockerfile
Pinning `node-sass@3.8.0` prevents https://github.com/inspirehep/inspire-next/issues/1642 from happening.
Closes https://github.com/inspirehep/inspire-next/issues/1642
=> python_base: pin node-sass

elasticsearch/Dockerfile
* Needed by invenio-records-files>=v1.0.0a8.
Signed-off-by: Javier Martin Montull <javier.martin.montull@cern.ch>
=> elasticsearch: mapper-attachments plugin addition

python_base/Dockerfile
I have added those two lines in order to define the stable dependencies for the inspire-next project. This allow us to run 2 different test suits. 
- One with the dependencies that for sure work  
- One with the unstable dependencies that might not work
=> python_base: create stable deps file

README.md
The `docker build` was missing a dot.
=> readme: fix the command line for the docker build

python_base/Dockerfile
This change should remove the `inspirehep` package. It is necessary to run the tests for this PR (https://github.com/inspirehep/inspire-next/pull/1810). Now the tests are failing because `pip` is trying to install the package of `Inspirehep` https://travis-ci.org/inspirehep/inspire-next/jobs/183907796.
=> python_base: remove inspire pkg stable deps file

python_base/Dockerfile
@david-caro made me realize that the reason `inspire-nightly` does not serve SVGs is because it does not know about them : )
=> python_base: add mailcap

python_base/Dockerfile
Adding firefox, in order to have a visible browser when we run acceptance tests
=> python_base: add firefox for acceptance tests

README.md, python_base/Dockerfile, python_base/docker_entrypoint.sh, test.sh
Closes #33
Since version 34 `setuptools` requires a recent enough version of
`pip` to be installed.
When running the tests we need to override the `latest` tag for the
image that we want to test so that `docker-compose` does not pull it
from the repo.
Finally, we pin `clean-css` to the `^3.4.23` release because the
`4.x` release introduced several breaking changes in features we
depend on.
=> python_base: fix build

README.md
Changes only the command to pull the `python-base` image
=> docs: minor fix in the documentation

python_base/Dockerfile
* Adds `make` command for script that executes unit tests and generates documentation for Inspire-hep.
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> python_base: add make command for makefiles

python_base/Dockerfile
* Adds `docs` requirements to generate documentation.
Addresses https://github.com/inspirehep/inspire-next/pull/1982
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> python_base: add docs requirements for install

elasticsearch/Dockerfile
Tonight ElasticHQ updated itself to support Elasticsearch 5, so the build started failing because we require the latest version from `master`. According to the documentation (https://github.com/royrusso/elasticsearch-HQ), `v2.0.3` is the latest to support Elasticsearch 2.
=> elasticsearch: pin version of ElasticHQ

python_base/Dockerfile, python_base/docker_entrypoint.sh
Should be removed once https://github.com/pypa/setuptools/pull/1044
is merged.
=> fix: pin setuptools version due to bad import

python_base/Dockerfile, python_base/docker_entrypoint.sh
Reverts commit 2dd5926 because `setuptools==36.0.1` was released,
fixing the import bug.
=> fix: unpin setuptools

python_base/docker_entrypoint.sh
The containers got in a race condition sometimes where the chown tried
to change the ownership of the '.pyc' files while they were removed by
another container, failing to run the docker_entrypoint script and
failing to start the container. Now it will ignore such errors and
just continue running (if there were serious issues, it will fail to
run the tests).
Fixes https://github.com/inspirehep/inspire-next/issues/2385
=> python_base: don't fail to start on chown error

python_base/Dockerfile
It turns out that the package was moved to rhel 7.4 repos, so it was
removed from epel, will not be needed once the base centos images
are upgraded. See:
https://bugzilla.redhat.com/show_bug.cgi?id=1481008
=> python_base: add explicit http-parser dependency

python_base/Dockerfile
* It turns out that the package was moved to rhel 7.4 repos, so it was
removed from epel, will not be needed once the base centos images
are upgraded. See:
https://bugzilla.redhat.com/show_bug.cgi?id=1481008
=> Fix http-parser missing package

test.sh
Similarly to https://github.com/inspirehep/inspire-next/pull/2476,
removes a minor source of flakiness by retrying the creation of
assets in case it fails.
=> test: retry assets creation

python_base/Dockerfile
Makes the workaround introduced in 2698570 obsolete as now the package
is normally available (closes #52).
=> python_base: pin centos to 7.4.1708

python_base/Dockerfile
inspirehep/inspire-next#2823 changed how we install dependencies in
`inspire-next`, so this commit makes them the same again.
=> python_base: install dependencies the same way

python_base/Dockerfile
* This was making some harvests fail with the error 'unable to open
file /tmp/magick-...' as it was actually unable to generate that
file.
=> python-base: install missing package to get fig2dev

.travis.yml
Fixes the build by using the older Trusty image, which comes with
an older version of ``docker-ce`` whose ``login`` command still
supports the ``--email`` option.
Clearly the better fix is to remove this option from the script, but I
couldn't figure out which of the three secure variables is storing
the email... https://github.com/inspirehep/inspire-docker/blob/ee9a80dc947e5f60c0c39aaa3215ac572cf1ba3c/.travis.yml#L10-L12
=> travis: use deprecated Trusty image

python_base/Dockerfile
It's needed to run the selenium tests out of travis.
=> python_base: add Xvfb package

python_base/fix_rights.c
simple typo fix in Usage string, no functional change
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
=> fixes typo in Usage string
